// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLhgoeQH4ixubrH3pF893mKAbB1BZuKVc',
    appId: '1:364696211753:web:0d46c1d95daf557a726738',
    messagingSenderId: '364696211753',
    projectId: 'social-media-b5d9c',
    authDomain: 'social-media-b5d9c.firebaseapp.com',
    storageBucket: 'social-media-b5d9c.appspot.com',
    measurementId: 'G-JQEJ7WB56W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7W50joaUzlcmSWeRHQWVfQMqh0NIAhPw',
    appId: '1:364696211753:android:df7bd36846897e41726738',
    messagingSenderId: '364696211753',
    projectId: 'social-media-b5d9c',
    storageBucket: 'social-media-b5d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7kbNPdxeSiqB0Kln672SZYl_sV5PzxFk',
    appId: '1:364696211753:ios:c6d0c3db4fc180ac726738',
    messagingSenderId: '364696211753',
    projectId: 'social-media-b5d9c',
    storageBucket: 'social-media-b5d9c.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7kbNPdxeSiqB0Kln672SZYl_sV5PzxFk',
    appId: '1:364696211753:ios:678720c22819f8cc726738',
    messagingSenderId: '364696211753',
    projectId: 'social-media-b5d9c',
    storageBucket: 'social-media-b5d9c.appspot.com',
    iosBundleId: 'com.example.socialMedia.RunnerTests',
  );
}
